/*                              chk_db.c                            */
/* The purpose of this program is to check a parts database for :-  */
/*    (a) Duplication of part numbers.                              */
/*    [(b) Valid data in numeric fields, e.g. 0 to 'n'.]            */                                        
/*    [(c) Only ASCII characters in strings.]                       */

/*
CHK_DB.C

The purpose of this program is to check a parts database for :-
   (a) Duplication of part numbers.                  
  [(b) Valid data in numeric fields, e.g. 0 to 'n'.]                                         
  [(c) Only ASCII characters in strings.]  

The input to the program is data file of the type generated by MK_DBASE.C; the
actual name of the file is user specified. The output is written directly to
the screen.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../ck_utils/ck_types.h"
#include "../ck_utils/ck_utils.h"

int check_dbase(struct part_info *base_ptr);

void main(int argc,
          char *argv[])
   {
   FILE *fptr_db;
   struct part_info *base_ptr;

   if ((fptr_db = fopen(argv[1],"rb")) == NULL)
      {
      printf("Cannot open file %s \n",argv[1]);
      exit(0);
      }
   if ((base_ptr = read_tgt_dbase(fptr_db)) == NULL)
      {
      printf("Insufficient memory for target database\n");
      exit(0);
      }
   else
      {
      check_dbase(base_ptr);
      }
   _fcloseall();
   }  /* main() */

int check_dbase(struct part_info *base_ptr)
   {
   struct part_info *source_ptr;
   struct part_info *search_ptr;

   source_ptr = base_ptr;
   while (source_ptr->part_ptr != NULL)
      {
      search_ptr = source_ptr->part_ptr;
      while (search_ptr->part_ptr != NULL)
         {
	 if (strcmp(source_ptr->part_number,search_ptr->part_number) == 0)
            {
	    printf("Duplicate part number found : %s\n",source_ptr->part_number);
	    printf("   %s\n",source_ptr->description);
	    printf("   %s\n",search_ptr->description);
	    }
         search_ptr = search_ptr->part_ptr;
         }
      source_ptr = source_ptr->part_ptr;
      }
   return 1;
   }   /* check_dbase() */
